# Generated by Django 4.2.3 on 2025-07-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
